name: Helm deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      claim_api_environment_name:
        required: true
        type: string
        description: The name of the environment which Claims API is deployed to
      image_tag:
        required: true
        type: string
    secrets:
      pact_broker_username:
        required: true
      pact_broker_password:
        required: true
      kube_cert:
        required: true
      KUBE_CLUSTER:
        required: true
      KUBE_TOKEN:
        required: true
      KUBE_NAMESPACE:
        required: true
      LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_ROLE_TO_ASSUME:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set branch name
        run: echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}" >> $GITHUB_ENV

      - name: Can I deploy?
        id: can-i-deploy
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-can-i-deploy@035ee98ca0047659f865532ea6234abd69529ee8 # v2.5.0
        with:
          pacticipant: 'laa-data-claims-event-service'
          environment: ${{ inputs.claim_api_environment_name }}
          pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
          pact_broker_username: ${{ secrets.pact_broker_username }}
          pact_broker_password: ${{ secrets.pact_broker_password }}

      - name: Authenticate to the cluster
        run: |
          echo "${{ secrets.kube_cert }}" > ca.crt
          kubectl config set-cluster ${{ secrets.KUBE_CLUSTER }} --certificate-authority=./ca.crt --server=https://${{ secrets.KUBE_CLUSTER }}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${{ secrets.KUBE_CLUSTER }} --cluster=${{ secrets.KUBE_CLUSTER }} --user=deploy-user --namespace=${{ secrets.KUBE_NAMESPACE }}
          kubectl config use-context ${{ secrets.KUBE_CLUSTER }}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: ${{ secrets.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_REGION }}

      - name: Login ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        id: login-ecr

      - name: Set helm chart app version
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          # use env var to avoid injecting github context directly into the shell
          yq eval-all "( .appVersion = \"$IMAGE_TAG\" )" -i helm-chart/Chart.yaml
          cat helm-chart/Chart.yaml

      - name: Install or upgrade helm charts
        id: helm-install
        env:
          DEPLOYMENT_NAME: ${{ inputs.deployment_name }}
          ENV_VALUES_FILE: "helm-chart/values/env-${{ inputs.environment }}.yaml"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_REPOSITORY }}
        run: |
          echo "Deploying Helm release '$DEPLOYMENT_NAME'..."
          helm upgrade --install --wait --timeout 15m \
            -f "$ENV_VALUES_FILE" \
            "$DEPLOYMENT_NAME" helm-chart \
            --set image.repository="$REGISTRY/$REPOSITORY"

          REG_REPO="$REGISTRY/$REPOSITORY"
          IMAGES=$(helm get manifest "$DEPLOYMENT_NAME" | yq -o=json '.' | jq -sc --arg registry "$REG_REPO" '[.[] | select(.kind == "Deployment") | select(.spec.template.spec.containers[0].image | contains($registry)) | {image_version_tag: .metadata.labels.appVersion, release_tag: .metadata.name}]')

          echo "images=$IMAGES" >> $GITHUB_OUTPUT
          echo "Deployed Images: $(echo "$IMAGES" | jq)"

      - name: Record deployment to pact broker
        id: record-deployment-to-pact-broker
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-record-deployment@035ee98ca0047659f865532ea6234abd69529ee8 # v2.5.0
        with:
          pacticipant: 'laa-data-claims-event-service'
          environment: ${{ inputs.claim_api_environment_name }}
          pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
          pact_broker_username: ${{ secrets.pact_broker_username }}
          pact_broker_password: ${{ secrets.pact_broker_password }}
